version: "3.9"
services:

  postrgre-db:
    image: postgres:15
    container_name: postrgre
    ports:
      - 5432:5432
    env_file:
      - .env-for-compose
    

  fastapi-app:
    build: 
      context: .
    env_file:
    - .env-for-compose
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - postrgre-db
    command: alembic upgrade 84e085e68efe
      && alembic upgrade 8a276ed575be
      && ./bot
      && python3 main.py
      && ../srs
      && uvicorn main:app --host 127.0.0.1 --port 8000
  
    

  # tg-bot:
  #   env_file:
  #   - .env-for-compose
  #   container_name: tg_bot
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - postrgre-db
  #     - fastapi-app
  #   working_dir: ./bot
  #   command: python main.py
