"""added tgname

Revision ID: 8a276ed575be
Revises: 84e085e68efe
Create Date: 2024-05-12 16:06:50.348602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a276ed575be'
down_revision: Union[str, None] = '84e085e68efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('verify_tg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verify_tg')
    op.drop_column('user', 'tg_name')
    # ### end Alembic commands ###
